root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

django.request - WARNING - Not Found: /create/adityagator.github.io
root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Autoregressive Moving Average on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 43, in process_demo
    rmse, mape, pred = algo_obj.get_predictions_rmse_mape(algo_name)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 124, in get_predictions_rmse_mape
    model_fit = model.fit(disp=0)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 985, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 577, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py", line 555, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New COVID Positive Cases
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

tensorflow - WARNING - 5 out of the last 124 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f90d8f6e670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on Hospitalized Currently due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

root - ERROR - Error while using Simple Exponential Smoothing on New Deaths due to COVID
root - ERROR - Traceback (most recent call last):
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/process_demo.py", line 96, in process_demo
    opt = minimize(algo_obj.holt_winters_function, x0=x,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 406, in _minimize_tnc
    rc, nf, nit, x = moduleTNC.minimize(func_and_grad, x0, low, up, scale,
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/env/lib/python3.8/site-packages/scipy/optimize/tnc.py", line 366, in func_and_grad
    f = fun(x, *args)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 220, in holt_winters_function
    mape = self.mean_absolute_percentage_error(predictions)
  File "/Users/adityabharadwaj/Documents/smart4kast2/time-series-forecasts/time-forecast-app/processing/algorithms.py", line 92, in mean_absolute_percentage_error
    ans = abs((y_true[i] - y_pred[i]) / y_true[i]) * 100
IndexError: index 12 is out of bounds for axis 0 with size 12

